env=PROD
browser=chrome
timeout.implicit=2
timeout.explicit=15
headless=true
test.data.path=src/test/resources/TestData/TestData.xlsx
api.key=reqres_dcd611de310b44aba1bb9afcae144a05

# Stable public demo practice site
ui.base.url=https://www.saucedemo.com/
ui.login.page=https://www.saucedemo.com/
api.base.uri=https://reqres.in
