env=QA
browser=chrome
timeout.implicit=10
timeout.explicit=15
headless=false

# Stable public demo practice site
ui.base.url=https://practice.expandtesting.com
ui.login.page=https://practice.expandtesting.com/login

api.base.uri=https://practice.expandtesting.com/api