env=QA
browser=chrome
timeout.implicit=10
timeout.explicit=15
headless=true
test.data.path=src/test/resources/TestData/TestData.xlsx

# Stable public demo practice site
ui.base.url=https://www.saucedemo.com/
ui.login.page=https://practice.expandtesting.com/login

api.base.uri=https://practice.expandtesting.com/api