# QA Environment Matrix
env=QA
browser=chrome
timeout.implicit=10
timeout.explicit=15

# UI Front-End Web Application Endpoints
ui.baseUrl=https://preview.juice-shop.herokuapp.com

# Backend REST API Core System Endpoints
api.baseUri=https://preview.juice-shop.herokuapp.com/api
