# Production QA Environment Matrix
env=PROD
browser=chrome
timeout.implicit=8
timeout.explicit=12

# UI Front-End Web Application Endpoints
ui.baseUrl=https://preview.juice-shop.herokuapp.com

# Backend REST API Core System Endpoints
api.baseUri=https://preview.juice-shop.herokuapp.com/api
